# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/movie-recommender',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/movie-recommender',
                'lib_path': 'movie_recommender'},
  'syms': {'movie_recommender.core': {'movie_recommender.core.foo': ('core.html#foo', 'movie_recommender/core.py')}}}