# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/movie-recommender',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/movie-recommender',
                'lib_path': 'movie_recommender'},
  'syms': { 'movie_recommender.core': {'movie_recommender.core.foo': ('core.html#foo', 'movie_recommender/core.py')},
            'movie_recommender.movie_recommender': { 'movie_recommender.movie_recommender.get_movie_recs': ( 'movie_recommender.html#get_movie_recs',
                                                                                                             'movie_recommender/movie_recommender.py'),
                                                     'movie_recommender.movie_recommender.search_movies_n_recommend': ( 'movie_recommender.html#search_movies_n_recommend',
                                                                                                                        'movie_recommender/movie_recommender.py')}}}